// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: shard.proto

// Internal API: coordinator -> shard. Never exposed to end clients.
//
// A shard owns exactly one durable.Index and knows nothing about any other
// shard. All routing, fan-out and merging lives in the coordinator, which
// keeps this service trivially testable in isolation.

package shardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Key identifies a vector. Two different clients may pick the same label for
// unrelated vectors, so identity is the whole (client_id, label) pair.
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      uint64                 `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Label         uint64                 `protobuf:"varint,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Key) GetLabel() uint64 {
	if x != nil {
		return x.Label
	}
	return 0
}

type ScoredKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredKey) Reset() {
	*x = ScoredKey{}
	mi := &file_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredKey) ProtoMessage() {}

func (x *ScoredKey) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredKey.ProtoReflect.Descriptor instead.
func (*ScoredKey) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{1}
}

func (x *ScoredKey) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScoredKey) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// NOTE ON `repeated float`: proto3 packs repeated scalar numeric fields by
// default, so no [packed = true] annotation is needed. The wire cost is
// 4 bytes per dimension plus a length prefix -- 3076 bytes for a 768-dim
// vector, which is why bulk loading should eventually use a client-streaming
// RPC rather than one unary call per vector.
type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{2}
}

func (x *InsertRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{5}
}

type UndeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteRequest) Reset() {
	*x = UndeleteRequest{}
	mi := &file_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteRequest) ProtoMessage() {}

func (x *UndeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteRequest.ProtoReflect.Descriptor instead.
func (*UndeleteRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{6}
}

func (x *UndeleteRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type UndeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeleteResponse) Reset() {
	*x = UndeleteResponse{}
	mi := &file_shard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeleteResponse) ProtoMessage() {}

func (x *UndeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeleteResponse.ProtoReflect.Descriptor instead.
func (*UndeleteResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{7}
}

type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query []float32              `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	K     uint32                 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	// ef controls the recall/latency tradeoff. 0 means "use the shard's
	// configured default", so the coordinator does not have to know it.
	Ef            uint32 `protobuf:"varint,3,opt,name=ef,proto3" json:"ef,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_shard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{8}
}

func (x *SearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SearchRequest) GetK() uint32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetEf() uint32 {
	if x != nil {
		return x.Ef
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredKey           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_shard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResponse) GetResults() []*ScoredKey {
	if x != nil {
		return x.Results
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_shard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{10}
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_shard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{11}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_shard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{12}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalVectors  uint64                 `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`    // includes tombstoned
	ActiveVectors uint64                 `protobuf:"varint,2,opt,name=active_vectors,json=activeVectors,proto3" json:"active_vectors,omitempty"` // excludes tombstoned
	Dim           uint32                 `protobuf:"varint,3,opt,name=dim,proto3" json:"dim,omitempty"`
	Capacity      uint64                 `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"` // fixed at construction
	MemoryBytes   uint64                 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_shard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{13}
}

func (x *StatsResponse) GetTotalVectors() uint64 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *StatsResponse) GetActiveVectors() uint64 {
	if x != nil {
		return x.ActiveVectors
	}
	return 0
}

func (x *StatsResponse) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *StatsResponse) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StatsResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

var File_shard_proto protoreflect.FileDescriptor

const file_shard_proto_rawDesc = "" +
	"\n" +
	"\vshard.proto\x12\x15vectorsearch.shard.v1\"8\n" +
	"\x03Key\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x04R\bclientId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\x04R\x05label\"U\n" +
	"\tScoredKey\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.vectorsearch.shard.v1.KeyR\x03key\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"U\n" +
	"\rInsertRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.vectorsearch.shard.v1.KeyR\x03key\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"\x10\n" +
	"\x0eInsertResponse\"=\n" +
	"\rDeleteRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.vectorsearch.shard.v1.KeyR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"?\n" +
	"\x0fUndeleteRequest\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.vectorsearch.shard.v1.KeyR\x03key\"\x12\n" +
	"\x10UndeleteResponse\"C\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\rR\x01k\x12\x0e\n" +
	"\x02ef\x18\x03 \x01(\rR\x02ef\"L\n" +
	"\x0eSearchResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .vectorsearch.shard.v1.ScoredKeyR\aresults\"\x11\n" +
	"\x0fSnapshotRequest\"\x12\n" +
	"\x10SnapshotResponse\"\x0e\n" +
	"\fStatsRequest\"\xac\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x04R\ftotalVectors\x12%\n" +
	"\x0eactive_vectors\x18\x02 \x01(\x04R\ractiveVectors\x12\x10\n" +
	"\x03dim\x18\x03 \x01(\rR\x03dim\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x04R\bcapacity\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x04R\vmemoryBytes2\xa1\x04\n" +
	"\fShardService\x12U\n" +
	"\x06Insert\x12$.vectorsearch.shard.v1.InsertRequest\x1a%.vectorsearch.shard.v1.InsertResponse\x12U\n" +
	"\x06Delete\x12$.vectorsearch.shard.v1.DeleteRequest\x1a%.vectorsearch.shard.v1.DeleteResponse\x12[\n" +
	"\bUndelete\x12&.vectorsearch.shard.v1.UndeleteRequest\x1a'.vectorsearch.shard.v1.UndeleteResponse\x12U\n" +
	"\x06Search\x12$.vectorsearch.shard.v1.SearchRequest\x1a%.vectorsearch.shard.v1.SearchResponse\x12[\n" +
	"\bSnapshot\x12&.vectorsearch.shard.v1.SnapshotRequest\x1a'.vectorsearch.shard.v1.SnapshotResponse\x12R\n" +
	"\x05Stats\x12#.vectorsearch.shard.v1.StatsRequest\x1a$.vectorsearch.shard.v1.StatsResponseB\x1eZ\x1chnswdb/proto/shardpb;shardpbb\x06proto3"

var (
	file_shard_proto_rawDescOnce sync.Once
	file_shard_proto_rawDescData []byte
)

func file_shard_proto_rawDescGZIP() []byte {
	file_shard_proto_rawDescOnce.Do(func() {
		file_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)))
	})
	return file_shard_proto_rawDescData
}

var file_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_shard_proto_goTypes = []any{
	(*Key)(nil),              // 0: vectorsearch.shard.v1.Key
	(*ScoredKey)(nil),        // 1: vectorsearch.shard.v1.ScoredKey
	(*InsertRequest)(nil),    // 2: vectorsearch.shard.v1.InsertRequest
	(*InsertResponse)(nil),   // 3: vectorsearch.shard.v1.InsertResponse
	(*DeleteRequest)(nil),    // 4: vectorsearch.shard.v1.DeleteRequest
	(*DeleteResponse)(nil),   // 5: vectorsearch.shard.v1.DeleteResponse
	(*UndeleteRequest)(nil),  // 6: vectorsearch.shard.v1.UndeleteRequest
	(*UndeleteResponse)(nil), // 7: vectorsearch.shard.v1.UndeleteResponse
	(*SearchRequest)(nil),    // 8: vectorsearch.shard.v1.SearchRequest
	(*SearchResponse)(nil),   // 9: vectorsearch.shard.v1.SearchResponse
	(*SnapshotRequest)(nil),  // 10: vectorsearch.shard.v1.SnapshotRequest
	(*SnapshotResponse)(nil), // 11: vectorsearch.shard.v1.SnapshotResponse
	(*StatsRequest)(nil),     // 12: vectorsearch.shard.v1.StatsRequest
	(*StatsResponse)(nil),    // 13: vectorsearch.shard.v1.StatsResponse
}
var file_shard_proto_depIdxs = []int32{
	0,  // 0: vectorsearch.shard.v1.ScoredKey.key:type_name -> vectorsearch.shard.v1.Key
	0,  // 1: vectorsearch.shard.v1.InsertRequest.key:type_name -> vectorsearch.shard.v1.Key
	0,  // 2: vectorsearch.shard.v1.DeleteRequest.key:type_name -> vectorsearch.shard.v1.Key
	0,  // 3: vectorsearch.shard.v1.UndeleteRequest.key:type_name -> vectorsearch.shard.v1.Key
	1,  // 4: vectorsearch.shard.v1.SearchResponse.results:type_name -> vectorsearch.shard.v1.ScoredKey
	2,  // 5: vectorsearch.shard.v1.ShardService.Insert:input_type -> vectorsearch.shard.v1.InsertRequest
	4,  // 6: vectorsearch.shard.v1.ShardService.Delete:input_type -> vectorsearch.shard.v1.DeleteRequest
	6,  // 7: vectorsearch.shard.v1.ShardService.Undelete:input_type -> vectorsearch.shard.v1.UndeleteRequest
	8,  // 8: vectorsearch.shard.v1.ShardService.Search:input_type -> vectorsearch.shard.v1.SearchRequest
	10, // 9: vectorsearch.shard.v1.ShardService.Snapshot:input_type -> vectorsearch.shard.v1.SnapshotRequest
	12, // 10: vectorsearch.shard.v1.ShardService.Stats:input_type -> vectorsearch.shard.v1.StatsRequest
	3,  // 11: vectorsearch.shard.v1.ShardService.Insert:output_type -> vectorsearch.shard.v1.InsertResponse
	5,  // 12: vectorsearch.shard.v1.ShardService.Delete:output_type -> vectorsearch.shard.v1.DeleteResponse
	7,  // 13: vectorsearch.shard.v1.ShardService.Undelete:output_type -> vectorsearch.shard.v1.UndeleteResponse
	9,  // 14: vectorsearch.shard.v1.ShardService.Search:output_type -> vectorsearch.shard.v1.SearchResponse
	11, // 15: vectorsearch.shard.v1.ShardService.Snapshot:output_type -> vectorsearch.shard.v1.SnapshotResponse
	13, // 16: vectorsearch.shard.v1.ShardService.Stats:output_type -> vectorsearch.shard.v1.StatsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_shard_proto_init() }
func file_shard_proto_init() {
	if File_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shard_proto_goTypes,
		DependencyIndexes: file_shard_proto_depIdxs,
		MessageInfos:      file_shard_proto_msgTypes,
	}.Build()
	File_shard_proto = out.File
	file_shard_proto_goTypes = nil
	file_shard_proto_depIdxs = nil
}
